ignorePatterns:
  - "dist"
parser: "@typescript-eslint/parser"
rules:
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/prefer-namespace-keyword": off
  "no-empty": off
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
