export type { Ace } from "ace-builds"
export * from "./AcePlayer"
export * from "./AceRecorder"
export * from "./AceRecordReplayer"
export * from "./AceStreamer"
export * from "./AudioRecorder"
export * from "./AudioRecordReplayer"
export * from "./types"
import { RecordReplayer } from "./RecordReplayer"
export default RecordReplayer
